### ISSUE TITLE
Avoid overwriting the base ipkg file when building

### ISSUE THREAD

**Issue by MarcelineVQ** [DoctorRainer/sae#1]
Currently when I build a project with sae it will overwrite my project's ipkg file with a new (versioned) name and just the fields it requires to build.
This is lossy since some fields aren't preserved and due to the name field being changed it could cause incompatibility with other tools and methods that might use the ipkg file.
I'd like to propose that we output a new ipkg file and operate off that when building a project. e.g. given `curl.ipkg` of
```
package curl

version    = "0.16.3.0"
...
```
`sae build` would result in a `curl-0_16_3_0.ipkg` file that sae works from instead of overwriting the content of a curl.ipkg

**Comment by DoctorRainer** [comment]
Hm, do we really need it? It's possible to change either name of .ipkg file or the package field in Eq.yml to avoid this. If it's a no-go, then I think it's possible to generate a file named Eq.ipkg or something of the sort, although, I think it would be more consistent if tools supported sae instead

**Comment by MarcelineVQ** [comment]
Oh I see! It's overwriting `curl.ipkg` because the package field in Eq.yaml is `package: curl` ? That's unfortunate since I think there's merit to keeping the same name in each place. If for no other reason than you don't need to remember multiple names for one library.
We don't necessarily need an extra ipkg file, aside from if there's an issue when building a person can examine the generated ipkg directly, I just didn't want my project's ipkg file to be modified since it's not only sae that uses it.  
With that in mind though I think what I'll do is adopt naming my package's ipkg `package.ipkg` for all my projects and let the name/package field determine the actual name. This should simplify things for tooling I make too since they'll have a common name to look for.

Thanks for the discussion, changing my ipkg name is enough of a solution for me.

**Comment by DoctorRainer** [comment]
Okay :)
